import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  sigobdiagSidebar: [
    'sig/obdiag/sig_intro',
    'sig/obdiag/sig_members',
    'sig/obdiag/join_us',
    'sig/obdiag/intro',
    'sig/obdiag/meeting',
    'sig/obdiag/other'
  ],
  sigartificial_intelligenceSidebar: [
    'sig/artificial-intelligence/sig_intro',
    'sig/artificial-intelligence/sig_members',
    'sig/artificial-intelligence/join_us',
    'sig/artificial-intelligence/intro',
    'sig/artificial-intelligence/meeting',
    'sig/artificial-intelligence/other'
  ],
  sigcloud_nativeSidebar: [
    'sig/cloud-native/sig_intro',
    'sig/cloud-native/sig_members',
    'sig/cloud-native/join_us',
    'sig/cloud-native/intro',
    'sig/cloud-native/meeting',
    'sig/cloud-native/other'
  ],
  sigdevelop_toolsSidebar: [
    'sig/develop-tools/sig_intro',
    'sig/develop-tools/sig_members',
    'sig/develop-tools/join_us',
    'sig/develop-tools/intro',
    'sig/develop-tools/meeting',
    'sig/develop-tools/other'
  ],
  sigminiobSidebar: [
    'sig/miniob/sig_intro',
    'sig/miniob/sig_members',
    'sig/miniob/join_us',
    'sig/miniob/intro',
    'sig/miniob/meeting',
    'sig/miniob/other'
  ],
  sigoperation_managementSidebar: [
    'sig/operation-management/sig_intro',
    'sig/operation-management/sig_members',
    'sig/operation-management/join_us',
    'sig/operation-management/intro',
    'sig/operation-management/meeting',
    'sig/operation-management/other'
  ],
  legacySidebar: [
    {
      type: 'category',
      label: 'About OceanBase',
      items: [{
        type: 'autogenerated',
        dirName: 'about_oceanbase'
      }],
    },
    {
      type: 'category',
      label: 'Deploy Oceanbase',
      items: [{
        type: 'autogenerated',
        dirName: 'deploy_oceanbase',
      }]
    },
    {
      type: 'category',
      label: 'Deploy Tools',
      items: [{
        type: 'autogenerated',
        dirName: 'deploy_tools',
      }]
    },
    {
      type: 'category',
      label: 'Data Migration',
      items: [{
        type: 'autogenerated',
        dirName: 'data_migration',
      }]
    },
    {
      type: 'category',
      label: 'Operation Maintenance',
      items: [{
        type: 'autogenerated',
        dirName: 'operation_maintenance',
      }]
    },
    {
      type: 'category',
      label: 'Performance Tuning',
      items: [{
        type: 'autogenerated',
        dirName: 'performance_tuning',
      }]
    },
    {
      type: 'category',
      label: 'Trouble Shooting',
      items: [{
        type: 'autogenerated',
        dirName: 'trouble_shooting',
      }]
    },
    {
      type: 'category',
      label: 'Development Practice',
      items: [{
        type: 'autogenerated',
        dirName: 'development_practice',
      }]
    },
    {
      type: 'category',
      label: 'Solutions',
      items: [{
        type: 'autogenerated',
        dirName: 'solutions',
      }]
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{
        type: 'autogenerated',
        dirName: 'FAQ',
      }]
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [{
        type: 'autogenerated',
        dirName: 'appendix',
      }]
    },
  ]
}

export default sidebars

