import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  legacySidebar: [
    {
      type: 'category',
      label: 'About OceanBase',
      items: [{
        type: 'autogenerated',
        dirName: 'about_oceanbase'
      }],
    },
    {
      type: 'category',
      label: 'Deploy Oceanbase',
      items: [{
        type: 'autogenerated',
        dirName: 'deploy_oceanbase',
      }]
    },
    {
      type: 'category',
      label: 'Deploy Tools',
      items: [{
        type: 'autogenerated',
        dirName: 'deploy_tools',
      }]
    },
    {
      type: 'category',
      label: 'Data Migration',
      items: [{
        type: 'autogenerated',
        dirName: 'data_migration',
      }]
    },
    {
      type: 'category',
      label: 'Operation Maintenance',
      items: [{
        type: 'autogenerated',
        dirName: 'operation_maintenance',
      }]
    },
    {
      type: 'category',
      label: 'Performance Tuning',
      items: [{
        type: 'autogenerated',
        dirName: 'performance_tuning',
      }]
    },
    {
      type: 'category',
      label: 'Trouble Shooting',
      items: [{
        type: 'autogenerated',
        dirName: 'trouble_shooting',
      }]
    },
    {
      type: 'category',
      label: 'Development Practice',
      items: [{
        type: 'autogenerated',
        dirName: 'development_practice',
      }]
    },
    {
      type: 'category',
      label: 'Solutions',
      items: [{
        type: 'autogenerated',
        dirName: 'solutions',
      }]
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{
        type: 'autogenerated',
        dirName: 'FAQ',
      }]
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [{
        type: 'autogenerated',
        dirName: 'appendix',
      }]
    },
  ]
}

export default sidebars

